const faqs = [
  {
    question: 'How are course strategies generated?',
    answer:
      "Strategies are generated by analyzing a player's practice round data — including fairway hit rates, green in regulation percentages, scrambling stats, and putting averages on a hole-by-hole basis. The system identifies patterns across multiple rounds and recommends tee shot clubs, approach targets, and putting emphases based on each player's actual tendencies.",
  },
  {
    question: 'What does the confidence level on each hole mean?',
    answer:
      'High confidence means the strategy is based on consistent, repeatable data across 3+ rounds — these holes are auto-approved. Medium confidence means there is some data but variability in performance warrants a coach review. Low confidence means limited data is available and the coach should personally verify and adjust the recommendation.',
  },
  {
    question: 'How do I approve a strategy for a player?',
    answer:
      'Select the player from the home screen to generate their strategy. High-confidence holes are automatically approved. For medium and low confidence holes, review each card and click Approve. Once all flagged holes are reviewed, the Sign Off & Send to Player button becomes active.',
  },
  {
    question: 'What is Round Defense?',
    answer:
      'Round Defense allows you to record hole-by-hole audio commentary and a post-round press conference debrief for each player. These recordings help players review their decision-making and mental approach after a tournament round.',
  },
  {
    question: 'Can I edit a generated strategy before approving it?',
    answer:
      'Yes. Each hole card has an edit mode where you can update the recommended club, target line, approach strategy, and rationale. You can also add written coach notes. Edited holes are flagged so both coach and player know the recommendation was personalised.',
  },
  {
    question: 'How do I create a custom strategy for a specific tournament?',
    answer:
      'Navigate to Tournaments, select the player, and click Create Custom Strategy. The strategy builder lets you customise each hole using the Player 360 panel and course imagery alongside. Changes are saved per hole and reviewed before sign-off.',
  },
  {
    question: 'What data does the Player 360 panel show?',
    answer:
      'The Player 360 panel shows ClippD performance analytics including strokes gained by category, approach shot heat maps, around-the-green breakdowns, putting profiles by distance range, and hole-by-hole scoring summaries across all practice rounds on file.',
  },
  {
    question: 'Are strategy approvals saved permanently?',
    answer:
      "In the current demo version, approvals and coach notes are stored in-memory for your session. In the production system these will be persisted to the database, timestamped, and sent to the player's mobile app.",
  },
];

export default function FAQ() {
  return (
    <div className="space-y-6 max-w-3xl">
      <div className="bg-black rounded-apple shadow-apple-lg p-8 border border-gray-900">
        <h1 className="text-4xl font-semibold text-white tracking-tight">FAQ</h1>
        <p className="mt-3 text-base text-gray-300 font-light">
          Common questions about the GolfGo Coach Portal
        </p>
      </div>

      <div className="space-y-3">
        {faqs.map((faq, i) => (
          <div
            key={i}
            className="bg-white rounded-apple shadow-apple border border-gray-100 p-6"
          >
            <h2 className="text-base font-semibold text-black tracking-tight">{faq.question}</h2>
            <p className="mt-2 text-sm text-gray-600 font-light leading-relaxed">{faq.answer}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
